<?xml version="1.0" encoding="utf-8"?><Database Name="WebApp" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DAVID-PC\SQLEXPRESS;Initial Catalog=WebApp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebAppConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.contactInfo" Member="contactInfos">
    <Type Name="contactInfo">
      <Column Name="Keys" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[First Name]" Member="First_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Last Name]" Member="Last_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Home Phone]" Member="Home_Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="[Cell Phone]" Member="Cell_Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>